services:
  backend:
    build: ./backend
    container_name: backend-service
    # image: dualnoiz/sayonph-backend:latest
    ports: # remove on production
      - "5001:5000"
    environment:
      - PORT=5000
      - FRONTEND_PORT=8001
      - NODE_ENV=production
      - DB_USER=sayonph
      - DB_PASSWORD=sayonph19!
      - DB_NAME=db_sayonph
      - DB_HOST=postgres   # inside docker network, service name = host
      - DB_PORT=5432
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend-service
    # image: dualnoiz/sayonph-frontend:latest
    ports: # remove on production
      - "8001:80"
      # - "80:80"       # only frontend exposed
      # - "443:443"     # for HTTPS if added
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: db_sayonph
    restart: always
    ports: # remove on production
      - "5432:5432"
    environment:
      POSTGRES_USER: sayonph
      POSTGRES_PASSWORD: sayonph19!
      POSTGRES_DB: db_sayonph
    volumes:
      - db_sayonph_data:/var/lib/postgresql/data
      - ./scripts/init/sayonph.sql:/docker-entrypoint-initdb.d/sayonph.sql

volumes:
  db_sayonph_data:
