services:
  backend:
    build: ./backend
    container_name: backend-service
    ports: # remove on production
      - "5001:5000"
    environment:
      - PORT=5000
      - FRONTEND_PORT=8001
      - NODE_ENV=production
      - DB_USER=speedmate
      - DB_PASSWORD=speedmate19!
      - DB_NAME=db_speedmate
      - DB_HOST=postgres   # inside docker network, service name = host
      - DB_PORT=5432
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports: # remove on production
      - "8001:80"
      # - "80:80"       # only frontend exposed
      # - "443:443"     # for HTTPS if added
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: db_speedmate
    restart: always
    ports: # remove on production
      - "5432:5432"
    environment:
      POSTGRES_USER: speedmate
      POSTGRES_PASSWORD: speedmate19!
      POSTGRES_DB: db_speedmate
    volumes:
      - db_speedmate_data:/var/lib/postgresql/data
      - ./scripts/outputs/speedmate.sql:/docker-entrypoint-initdb.d/speedmate.sql

volumes:
  db_speedmate_data:
